### ISSUE TITLE
NetCDF currently not supported

### ISSUE THREAD

**Issue by seb-1** [conda-forge/cdo-feedstock#54] opened 2019-02-22 21:12 UTC
Issue: NetCDF currently not supported

The NetCDF format is widely used in the climate modelling community. Integrating NetCDF support in conda-forge cdo would allow an easy installation of cdo for many users. Currently, those who need NetCDF support have to compile cdo on their system.

<br/>
Current conda-forge cdo (<code>cdo -V</code>):
<details>

```
Libraries:
Filetypes: srv ext ieg grb1
     CDI library version : 1.9.5
 CGRIBEX library version : 1.9.1
    EXSE library version : 1.4.0
    FILE library version : 1.8.3

```
</details>

<br/>
Suggested library support <code>cdo -V</code>:
<details>

```
Libraries: HDF5/1.10.4 proj/5.2 curl/7.64.0
Filetypes: srv ext ieg grb1 grb2 nc1 nc2 nc4 nc4c nc5
     CDI library version : 1.9.5
GRIB_API library version : 2.9.0
  NetCDF library version : 4.6.1 of Dec 10 2018 12:31:57 $
    HDF5 library version : 1.10.4
    EXSE library version : 1.4.0
    FILE library version : 1.8.3

```
</details>

**Comment by ocefpaf** [comment] 2019-02-22 21:22
I'm assuming you are using the macOS version of the package. That is a known problem and, if you know enough about Macs we could use your help, see #15.

PS: the Linux version is fully functional though.

```
> cdo -V
Climate Data Operators version 1.9.6 (http://mpimet.mpg.de/cdo)
System: x86_64-pc-linux-gnu
CXX Compiler: /home/conda/feedstock_root/build_artifacts/cdo_1550155197086/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++ -fPIC -DPIC -g -O2 -std=c++11 -fopenmp -fPIC -DPIC -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/filipe/miniconda3/envs/CDO/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix -fopenmp 
CXX version : unknown
C Compiler: /home/conda/feedstock_root/build_artifacts/cdo_1550155197086/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc -fPIC -DPIC -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/filipe/miniconda3/envs/CDO/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix -fopenmp  
C version : unknown
F77 Compiler: /home/conda/feedstock_root/build_artifacts/cdo_1550155197086/_build_env/bin/x86_64-conda_cos6-linux-gnu-gfortran -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/filipe/miniconda3/envs/CDO/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix
F77 version : unknown
Features: 15GB 8threads C++11 Fortran DATA PTHREADS OpenMP45 HDF5 NC4/HDF5/threadsafe OPeNDAP UDUNITS2 PROJ.4 XML2 CURL FFTW3 SSE3
Libraries: HDF5/1.10.4 proj/5.2 xml2/2.9.8 curl/7.64.0
Filetypes: srv ext ieg grb1 grb2 nc1 nc2 nc4 nc4c nc5 
     CDI library version : 1.9.6
 cgribex library version : 1.9.2
 ecCodes library version : 2.12.0
  NetCDF library version : 4.6.2 of Dec 17 2018 19:36:03 $
    hdf5 library version : 1.10.4 threadsafe
    exse library version : 1.4.1
    FILE library version : 1.8.3
```

Closing this as a duplicate of #15

**Closed by ocefpaf** 2019-02-22 21:22 UTC

**Comment by Try2Code** [comment] 2019-02-25 10:04
@seb-1 you can also you the macports package of CDO as long as the conda-forge package does not provide all the features you want
